// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.1
// source: springcachepb/springcachepb.proto

package springcachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpringCacheClient is the client API for SpringCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpringCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type springCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewSpringCacheClient(cc grpc.ClientConnInterface) SpringCacheClient {
	return &springCacheClient{cc}
}

func (c *springCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/springcachepb.SpringCache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *springCacheClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/springcachepb.SpringCache/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpringCacheServer is the server API for SpringCache service.
// All implementations must embed UnimplementedSpringCacheServer
// for forward compatibility
type SpringCacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	mustEmbedUnimplementedSpringCacheServer()
}

// UnimplementedSpringCacheServer must be embedded to have forward compatible implementations.
type UnimplementedSpringCacheServer struct {
}

func (UnimplementedSpringCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSpringCacheServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedSpringCacheServer) mustEmbedUnimplementedSpringCacheServer() {}

// UnsafeSpringCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpringCacheServer will
// result in compilation errors.
type UnsafeSpringCacheServer interface {
	mustEmbedUnimplementedSpringCacheServer()
}

func RegisterSpringCacheServer(s grpc.ServiceRegistrar, srv SpringCacheServer) {
	s.RegisterService(&SpringCache_ServiceDesc, srv)
}

func _SpringCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpringCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/springcachepb.SpringCache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpringCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpringCache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpringCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/springcachepb.SpringCache/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpringCacheServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpringCache_ServiceDesc is the grpc.ServiceDesc for SpringCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpringCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "springcachepb.SpringCache",
	HandlerType: (*SpringCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SpringCache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _SpringCache_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "springcachepb/springcachepb.proto",
}
